# Generated by Django 2.0.6 on 2018-07-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_url', models.URLField()),
                ('Video_name', models.CharField(max_length=200)),
                ('Video_o', models.TextField()),
                ('Video_data', models.DateTimeField()),
                ('Video_likes', models.ImageField(default=0, upload_to='')),
            ],
            options={
                'db_table': 'Video',
            },
        ),
    ]
