# Generated by Django 2.0.6 on 2018-07-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shufic', '0002_auto_20180704_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_text', models.TextField()),
                ('Comment_Video', models.ForeignKey(on_delete=True, to='shufic.Video')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
    ]
